name = "cha-ching"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "cha-ching"
database_id = "c30fcea4-f3bb-463a-8092-efade8d12120"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
